name: Test
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Import cpp-container
        uses: actions/checkout@v5
        with:
          repository: ChicoState/cpp-container
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build container image
        run: docker build -t gtest .
      - name: Test in container
        run: docker run -t gtest
